#!/bin/bash
#./newHeader name
#creates header file called "name.h" with appropriate preprocessor statements
UPPER=`echo $1 | tr '[:lower:]' '[:upper:]'`
touch $1.h
echo -e "#ifndef __"$UPPER"_H__\n#define __"$UPPER"_H__\n#endif" >> $1.h
