syntax enable
colorscheme torte
set nocompatible
set autoindent
set smartindent
set number

set tabstop=2
set expandtab
set shiftwidth=2

"highlight lines longer than 80 chars
match DiffAdd '\%>80v.*'

"ease navigate between open files
map <Left> <C-w><Left>
map <Right> <C-w><Right>
map <Up> <C-w><Up>
map <Down> <C-w><Down>

"taglist
map <silent> tt :TlistToggle<CR>

"move between buffers
map <silent> <C-Left> :bnext<CR>
map <silent> <C-Right> :bprev<CR>

"svn
map su :!svn update<CR>

"folding
:noremap f zfa{
:noremap o zo

"prevents weird color changes when opening files and pressing first key
if &term =~ "xterm"
    set t_Co=256
endif
